name: CI

on: [push, pull_request]

jobs:
  build:

    # Use macOS for emulator hardware acceleration
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1   
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Gradle build
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew build
